# -*- coding: utf-8 -*-
"""MRS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OUfafpLgOQYgC2AcWl4Em_JhKfkoPzSY
"""

import numpy as np
import pandas as pd
import os
import warnings
import zipfile
import tensorflow as tf

from google.colab import files 
uploaded = files.upload()

zip = zipfile.ZipFile('ml-100k.zip')
zip.extractall()

header = ['user_id','item_id','rating','timestamp']
df = pd.read_csv('/content/ml-100k/u.data',sep = '\t',names = header)
df=df.dropna(how='any')
df=df.drop(columns=['timestamp'])
df

df['rating'].unique()

X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1))

ann.compile(optimizer = 'adam', loss = 'mean_squared_error')
ann.fit(X_train, y_train, batch_size=32, epochs=1000)
ann.save('MRS.h5')

y_pred = model.predict(X_test)
y_pred=np.round(y_pred)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))